### ISSUE TITLE
Support tags / ldflags

### ISSUE THREAD

**Issue by Luzifer** [Luzifer/gobuilder#12]
# Proposal

In order to enable users to use the full functionality of `go build` let them control build-tags and ldflags. Proposal for config change (`compile_flags`):

``` yaml

---
readme_file: frontend/help.md
triggers:
  - github.com/Luzifer/gobuilder/cmd/starter
artifacts:
  - frontend/*
version_file: VERSION
notify:
  - type: dockerhub
    target: https://registry.hub.docker.com[...]d59f8a5ab895/
    filter: success
compile_flags:
  tags: debug
  ldflags: -x main.version $(git describe --tags)
```
# Questions
- Are `-ccflags`, `-gccgoflags`, `-gcflags` required / useful in context it is currently not possible to do CGO compiles with GoBuilder?
- Should the above stated case (dynamic content in ldflags) be possible?
  - Possible security risk due to command execution
- How to specify multiple tags? (How does the `-tags` CLI param of `go build` need them to get passed? Documentation is not useful and all examples only use one tag…)
