### ISSUE TITLE
artifacts should be a map

### ISSUE THREAD

**Issue by jbenet** [Luzifer/gobuilder#13]
@Luzifer the artifacts section should be a map. we need to be able to rename things into the zip.

given something like this:

```
cmd/ipfs
├── .gobuilder.yml
├── README.md
├── dist
│   ├── LICENSE
│   ├── README.md
│   └── install.sh
├── ipfs
├── main.go
```

something like this:

``` yml

---
artifacts:
  README.md: dist/README.md
  LICENSE: dist/LICENSE
  install.sh: dist/install.sh
```

should work.

---

Currently, this:

``` yml

---
artifacts:
  - dist/README.md
  - dist/LICENSE
  - dist/install.sh
```

yields this: 

![](https://www.evernote.com/shard/s198/sh/f1ba06c3-551c-436e-b374-8e03058df6f0/26401d6f1d85041e9167903892efb572/deep/0/ipfs-3.png)

which is not what we want.
