### ISSUE TITLE
use .gobuilder file

### ISSUE THREAD

**Issue by jbenet** [Luzifer/gobuilder#4]
would be nice to be able to define:
- project title (or default to github's)
- build flags
- one project multiple build targets
- markdown to render under the build listing (or default to the project's README.md)
- deprecate `.artifacts_file` and list those here.

(could be yaml or toml)

**Comment by jbenet** [comment]
(specifying more on building multiple targets.)

If i have a repo with multiple binaries, i could add each binary to gobuilder, but maybe i want to build all binaries into one archive and have people download them all together. so it would be nice to be able to specify either:
- a makefile to build them, or
- multiple go targets like this:

``` yml
targets:
 # bin/name: pkg/path
 ipfs: cmd/ipfs
 ipns: cmd/ipns
 tools/multihash: Godeps/_workspace/src/github.com/jbenet/go-multihash/multihash
 tools/multiaddr: Godeps/_workspace/src/github.com/jbenet/go-multiaddr-net/multiaddr
```

**Comment by jbenet** [comment]
``` yaml
targets:
  ipfs: 
    ipfs: cmd/ipfs/ipfs
    LICENSE: LICENSE
    Makefile: dist/Makefile
    README.md: dist/README.md
```

Would make an archive with `ipfs, LICENSE, Makefile, README.md`
